language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
  - composer install

addons:
  hosts:
    - testing.melon.io

script: ./vendor/bin/codecept run --steps
after_script:
  - ./vendor/bin/codecept run --coverage --coverage-xml
  - cp ./tests/_output/coverage.xml ./build/logs/clover.xml
  - ./vendor/bin/test-reporter

branches:
  only:
    - master
    - development